### ISSUE TITLE
Some Help Requested

### ISSUE THREAD

**Issue by hybras** [HaaLeo/publish-vscode-extension#1]
Your documentation is thorough and excellent. I'm new to gh actions though so pardon me..

I'm writing a workflow to publish [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer) to open-vsix.org. The repo is [here](https://github.com/hybras/Rust-Analyzer-Open-Vsix). I have a step to query github for the latest release and download the vsix file. It is successful. However, I'm having trouble passing it to the next step (yours, the publishing step). I'm getting `Error: Please specify either an extension file or a package path, but not both.` [I have not specified both keys](https://github.com/hybras/Rust-Analyzer-Open-Vsix/blob/master/.github/workflows/blank.yml#L34-L38). 

I understand you are under no obligation to help me, you published this action out of the goodness of your heart! Just close this issue then, I get it.

**Comment by HaaLeo** [comment]
Hi @hybras, thank you for your contribution. Let me break this issue down:

## Cause

This issue occurs since the default value for `packagePath` is `./`. Now in the workflow you additionally specify `extensionFile: rust-analyzer.vsix` &rarr; Both options are defined. 
You can see this also in the unfolded action log: 

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/23164374/87241870-8b6a7580-c427-11ea-963a-77c51b4d38c7.png">

## Solution
Similar to the second example in the README you must manually unset the `packagePath` option. I admit that this is probably somewhat unintuitive and in future releases I may reconsider this behaviour. However, for now the following snippet should solve your issue:
```yml
    - name: "Publish to Open VSX Registry"
      uses: HaaLeo/publish-vscode-extension@v0
      with:
        pat: ${{ secrets.OPEN_VSX_TOKEN }}
        extensionFile: "rust-analyzer.vsix"
        packagePath: ""
```

If you still experience any issues do not hesitate to file another issue.
