### ISSUE TITLE
`Error: Input required and not supplied: pat`

### ISSUE THREAD

**Issue by benrogmans** [HaaLeo/publish-vscode-extension#12]
While using this action with the following yml file:

```yaml
on:
  push:
    branches: [ main ]

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v0
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VSC_MARKETPLACE }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          packagePath: ''
```

I'm getting the error in the title of this issue. I found a workaround, which is to set the INPUT_PAT environment variables explicitly (together with the 'with.pat' option) like this:

```yaml
on:
  push:
    branches: [ main ]

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v0
        id: publishToOpenVSX
        env:
          INPUT_PAT: ${{ secrets.OPEN_VSX }}
        with:
          pat: ${{ secrets.OPEN_VSX }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        env:
          INPUT_PAT: ${{ secrets.VSC_MARKETPLACE }}
        with:
          pat: ${{ secrets.VSC_MARKETPLACE }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          packagePath: ''
```
