### ISSUE TITLE
open vsx publish errors are silently "swallowed" and not shown to the user

### ISSUE THREAD

**Issue by VladBrok** [HaaLeo/publish-vscode-extension#40]
| publish-vscode-extension Version | Operating System |
| -------------------------------------- | ---------------- |
| v1                                       |  lubuntu linux                |

# Description

open vsx publish errors are silently "swallowed" and not shown to the user
this happens because of the "allSettled" used here https://github.com/eclipse/openvsx/blob/master/cli/src/publish.ts (line 29)
more info: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

## Expected Behavior
All errors are shown to the user

## Actual Behavior
open vsx publish errors are silently "swallowed" and not shown to the user

# Steps to Reproduce
1. try to publish an extension to open vsx, but make an error intentionally, for example, specify a .vsix file that does not exist:
```
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: package.vsix #package.vsix does not exist
```
2. run CI
3. "publish the extension" section in the CI result will be empty:
![image](https://github.com/HaaLeo/publish-vscode-extension/assets/79661007/66641d3b-2df6-4ae3-bfcf-c75f79a9216f)
and extension is not published due to an error.

# Context
<details><pre><code>

</code></pre></details>
