### ISSUE TITLE
provide noVerify input param

### ISSUE THREAD

**Issue by AnWeber** [HaaLeo/publish-vscode-extension#8]
I am using this great github action to upload an extension for both openvsx and vsce. In my extension I need the setting enableProposedApi: true because I use the Noteboook Api. However, when publishing, this setting is blocked by vsce and [noVerify](https://github.com/microsoft/vscode-vsce/blob/b0c820449b7df5e34d0ebc5bd80cb3a6ecc90ea0/src/publish.ts) must be explicitly enabled.
According to [vsce#469](https://github.com/microsoft/vscode-vsce/issues/469) this setting is also the suggested solution

The best solution would probably be to be able to directly specify all possible parameters for both ovse and vsce.

```
- name: Publish to Visual Studio Marketplace
      uses: HaaLeo/publish-vscode-extension@v0
      with:
        pat: ${{ secrets.VSCE_TOKEN }}
        registryUrl: https://marketplace.visualstudio.com
        extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
        vsceOptions: 
            noVerify: true
        openvsxOptions: 
            ...
```

But if I read the api of @action/core correctly, only string is supported here and implementing the solution seems rather complex.

**Comment by HaaLeo** [comment]
Hi @AnWeber thx for raising this feature request. I also searched the docs and it seems it is only possible to pass string values to the `actions/core` API.
I think there are two main options here:
1. Passing in the vsce options as stringified JSON and parse them during runtime. This would allow us to clearly seperate between openvsx and vsce specific options. However, imho I think passing a JSON datastructure could be quite error prone and is quite unintuitive.
     ```yml
        - name: Publish to Visual Studio Marketplace
          uses: HaaLeo/publish-vscode-extension@v0
          with:
              pat: ${{ secrets.VSCE_TOKEN }}
              registryUrl: https://marketplace.visualstudio.com
              extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
              vsceOptions:  '{"noVerify": true}'
              openvsxOptions: '{}'
     ``` 
1. Introduce `noVerify` as top level option. Then vsce and vsx options will be mixed up at top level. I think this approach fits better into the specification of GitHub action inputs. And maybe we could clearly name it as `vsceNoVerify` or similar.
     ```yml
        - name: Publish to Visual Studio Marketplace
          uses: HaaLeo/publish-vscode-extension@v0
          with:
              pat: ${{ secrets.VSCE_TOKEN }}
              registryUrl: https://marketplace.visualstudio.com
              extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
              noVerify: true
     ```
